<a href="https://colab.research.google.com/github/mshravya12/bis_1wn24cs149/blob/main/week2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

def cost_function(x):
    cost = (x - 6)**2 + 10
    return cost

num_particles = 5
max_iterations = 6

w = 0.7
c1 = 1.5
c2 = 1.5

positions = np.random.uniform(0, 10, num_particles)

velocities = np.random.uniform(-1, 1, num_particles)

pbest_positions = positions.copy()

pbest_cost = cost_function(pbest_positions)

gbest_index = np.argmin(pbest_cost)

gbest_position = pbest_positions[gbest_index]

gbest_cost = pbest_cost[gbest_index]

for iteration in range(max_iterations):

    print("\n")
    print("========================================")
    print("ITERATION:", iteration + 1)
    print("========================================")

    current_cost = cost_function(positions)

    print("\nCurrent Positions:")
    print(positions)

    print("\nCurrent Costs:")
    print(current_cost)

    for i in range(num_particles):

        if current_cost[i] < pbest_cost[i]:

            pbest_positions[i] = positions[i]

            pbest_cost[i] = current_cost[i]

    print("\npBEST Positions:")
    print(pbest_positions)

    print("\npBEST Costs:")
    print(pbest_cost)

    best_index = np.argmin(pbest_cost)

    if pbest_cost[best_index] < gbest_cost:

        gbest_position = pbest_positions[best_index]

        gbest_cost = pbest_cost[best_index]

    print("\ngBEST Position:")
    print(gbest_position)

    print("gBEST Cost:")
    print(gbest_cost)

    r1 = np.random.random(num_particles)

    r2 = np.random.random(num_particles)

    velocities = (
        w * velocities
        + c1 * r1 * (pbest_positions - positions)
        + c2 * r2 * (gbest_position - positions)
    )

    print("\nNew Velocities:")
    print(velocities)

    positions = positions + velocities

    positions = np.clip(positions, 0, 10)

    print("\nNew Positions:")
    print(positions)

print("\n")
print("========================================")
print("FINAL RESULT")
print("========================================")

print("Best Delivery Center Location:",
      gbest_position, "km")

print("Minimum Delivery Cost:",
      gbest_cost)




ITERATION: 1

Current Positions:
[1.70892199 0.19835168 9.41967523 8.56446388 4.40978709]

Current Costs:
[28.41335047 43.65912321 21.6941787  16.57647499 12.52877709]

pBEST Positions:
[1.70892199 0.19835168 9.41967523 8.56446388 4.40978709]

pBEST Costs:
[28.41335047 43.65912321 21.6941787  16.57647499 12.52877709]

gBEST Position:
4.40978709154891
gBEST Cost:
12.528777094204473

New Velocities:
[-0.09953721  1.57134066 -7.22326326 -5.66103698  0.48892184]

New Positions:
[1.60938479 1.76969234 2.19641198 2.9034269  4.89870893]


ITERATION: 2

Current Positions:
[1.60938479 1.76969234 2.19641198 2.9034269  4.89870893]

Current Costs:
[29.27750196 27.8955029  24.46728184 19.58876497 11.21284202]

pBEST Positions:
[1.70892199 1.76969234 9.41967523 8.56446388 4.89870893]

pBEST Costs:
[28.41335047 27.8955029  21.6941787  16.57647499 11.21284202]

gBEST Position:
4.898708930762996
gBEST Cost:
11.212842019181185

New Velocities:
[ 4.48520175  3.30519711 -2.67338229  1.91280168  0.342245